# -*- coding: utf-8 -*-
"""API de Codificação e Decodificação.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16KuLhdXbzK3f3jUzQ5pNxDLaWj3ugRei
"""

import pandas as pd
from flask import Flask, request, jsonify

# Criação do dataframe
df = pd.DataFrame ({'1':[ 'a', 'f', 'k', 'p', 'u'],
                    '2':[ 'b', 'g', 'l', 'q', 'v'],
                    '3':[ 'c', 'h', 'm', 'r', 'w'],
                    '4':[ 'd', 'i', 'n', 's', 'x'],
                    '5':[ 'e', 'j', 'o', 't', 'y'],
                    '6':[ 'z', 'ñ', 'ç', 'z', 'z'],
                    })

# Função para Codificar (Letra -> Coordenada)
def buscar_coordenada(carac_bus, dataframe):
    carac_bus = str(carac_bus).lower()
    for x, row in dataframe.iterrows():
        for y, value in enumerate(row):
          if value == carac_bus:
            return f"{x},{y}"
    return "?"

# Função para Traduzir (Coordenada -> Letra)
def traduzir_coordenada(coord_bus, dataframe):
    try:
        x, y = map(int, coord_bus.split(','))
        return dataframe.iloc[x, y]
    except:
        return "?"

# Configurando flask(API)
app = Flask(__name__)

@app.route('/codificar', methods=['POST'])
def codificar_API():
    texto = request.json.get('texto', '')
    co = [buscar_coordenada(c, df) if c != ' ' else ' ' for c in texto]
    return jsonify({'resultado': " ".join(co)})

@app.route('/decodificar', methods=['POST'])
def decodificar_API():
    texto = request.json.get('coords', '')
    res = [traduzir_coordenada(c, df) for c in texto.split()]
    return jsonify({'resultado': "".join(res)})

try:
    sel = int(input("Digite 1 para codificar (Texto -> Coordenada) ou 2 para traduzir (Coordenada -> Texto): "))

    if sel == 1:
      ent = input("Digite o texto para codificar: ")
      co = [buscar_coordenada(carac, df) if carac != ' ' else ' ' for carac in ent]
      resultado_final = " ".join(co)
      print("\nResultado da Codificação:", resultado_final)

    elif sel == 2:
      ent = input("Digite as coordenadas para traduzir (ex: 0,0 0,1): ")
      res = [traduzir_coordenada(coord, df) for coord in ent.split()]
      resultado_final = "".join(res)
      print("\nResultado da Tradução:", resultado_final)

    if 'resultado_final' in locals():
      with open("resultado.txt", "w") as text:
          text.write(f"Resultado: {resultado_final}")
      print("Arquivo 'resultado.txt' gerado!")

except ValueError:
    print("Entrada inválida.")

# Teste API
import requests

res = requests.post(
    "http://127.0.0.1:5000/codificar",
    json={"texto": "abc"}
)

print(res.status_code)
print(res.text)